In [2]:
# a toy example --> 4 lobes, each one has 4 nodes, so 4 matrices 4x4
# generate four 4x4 random matrices with elements between 0 and 1 included
import os
import numpy as np
import matplotlib.pyplot as plt
from libraries.graphs import graph_draw
from G_matrices import healthy_matrices
from k_operator import tensor as k

In [3]:
output_dir = "graphs" # create a directory to save the plots
os.makedirs(output_dir, exist_ok=True)

if not os.path.exists('data'): # create the data directory if it does not exist
    os.makedirs('data')

In [4]:
healthy_names = ["healthy_a", "healthy_b", "healthy_c", "healthy_d"]
k_names = ["k_a", "k_b", "k_c", "k_d"]
# save each G matrix to a text file in the data directory
for name, matrix in zip(healthy_names, healthy_matrices):
    file_path = os.path.join('data', f"{name}.txt")
    np.savetxt(file_path, matrix)
    print(f"Saved {name} to {file_path}")

# save each matrix K to a text file in the data directory
for name, matrix in zip(k_names, k):
    file_path = os.path.join('data', f"{name}.txt")
    np.savetxt(file_path, matrix)
    print(f"Saved {name} to {file_path}")

# plot the graphs with the function graph_draw from deniz (to visualize up to 8 node graphs)
for i, (matrix, name) in enumerate(zip(healthy_matrices, healthy_names), 1):
    plt.figure(i)
    graph_draw(
        np.round(matrix, 2),
        Directed=False,
        Weighted=True,
        Index_on=True,
        Weight_on=False,
    )
    plt.title(name)
    plt.savefig(os.path.join(output_dir, f"{name}.png"))
    plt.close()

Saved healthy_a to data/healthy_a.txt
Saved healthy_b to data/healthy_b.txt
Saved healthy_c to data/healthy_c.txt
Saved healthy_d to data/healthy_d.txt
Saved k_a to data/k_a.txt
Saved k_b to data/k_b.txt
Saved k_c to data/k_c.txt
Saved k_d to data/k_d.txt


In [5]:
# for the first try we defined K-operator symmetric as well, so that the elementwise product generate a matrix that is 
# symmetric as well and on the graph we have no overlapping of numbers 
# apply the K-operator to the 4 matrices, element-wise operation

elementw_names = ["a_k_elwise", "b_k_elwise", "c_k_elwise", "d_k_elwise"]
elementw_matrices = [k[i] * healthy_matrices[i] for i in range(4)] # it's a 4x4x4 matrix
for name, matrix in zip(elementw_names, elementw_matrices):
    print(f"{name} =\n", matrix, "\n")

# plot the graphs with the function graph_draw from deniz (to visualize up to 8 node graphs)
for i, (matrix, name) in enumerate(zip(elementw_matrices, elementw_names), 1):
    plt.figure(i)
    graph_draw(
        np.round(matrix, 2),
        Directed=False,
        Weighted=True,
        Index_on=True,
        Weight_on=False,
    )
    plt.title(name)
    plt.savefig(os.path.join(output_dir, f"{name}.png"))
    plt.close()

# also save each element-wise multiplication matrix to a text file in the data directory
for name, matrix in zip(elementw_names, elementw_matrices):
    file_path = os.path.join('data', f"{name}.txt")
    np.savetxt(file_path, matrix)
    print(f"Saved {name} to {file_path}")

a_k_elwise =
 [[1.    0.285 0.058 0.119]
 [0.285 1.    0.183 0.268]
 [0.058 0.183 1.    0.243]
 [0.119 0.268 0.243 1.   ]] 

b_k_elwise =
 [[0.1   0.012 0.031 0.096]
 [0.012 0.1   0.028 0.096]
 [0.031 0.028 0.1   0.099]
 [0.096 0.096 0.099 0.1  ]] 

c_k_elwise =
 [[1.   0.85 0.09 0.78]
 [0.85 1.   0.14 0.58]
 [0.09 0.14 1.   0.35]
 [0.78 0.58 0.35 1.  ]] 

d_k_elwise =
 [[1.    0.3   0.166 0.602]
 [0.3   1.    0.261 0.128]
 [0.166 0.261 1.    0.135]
 [0.602 0.128 0.135 1.   ]] 

Saved a_k_elwise to data/a_k_elwise.txt
Saved b_k_elwise to data/b_k_elwise.txt
Saved c_k_elwise to data/c_k_elwise.txt
Saved d_k_elwise to data/d_k_elwise.txt


In [6]:
# apply the K-operator to the 4 matrices, row-column product
# also here, if K-operator is symmetric, we have a symmetric product 

rowcolumn_names = ["a_k_matmul", "b_k_mat_matmul", "c_k_matmul", "d_k_matmul"]
rowcolumn_matrices = [k[i] @ healthy_matrices[i] for i in range(4)] # it's a 4x4x4 matrix
for name, matrix in zip(rowcolumn_names, rowcolumn_matrices):
    print(f"{name} =\n", matrix, "\n")

# plot the graphs with the function graph_draw from deniz (to visualize up to 8 node graphs)
for i, (matrix, name) in enumerate(zip(rowcolumn_matrices, rowcolumn_names), 1):
    plt.figure(i)
    graph_draw(
        np.round(matrix, 2),
        Directed=False,
        Weighted=True,
        Index_on=True,
        Weight_on=False,
    )
    plt.title(name)
    plt.savefig(os.path.join(output_dir, f"{name}.png"))
    plt.close()

# also save each row by column multiplication matrix to a text file in the data directory
for name, matrix in zip(rowcolumn_names, rowcolumn_matrices):
    file_path = os.path.join('data', f"{name}.txt")
    np.savetxt(file_path, matrix)
    print(f"Saved {name} to {file_path}")

a_k_matmul =
 [[1.462 1.661 0.984 1.259]
 [1.225 1.736 1.163 1.236]
 [0.814 1.627 1.484 1.405]
 [1.359 2.018 1.617 1.63 ]] 

b_k_mat_matmul =
 [[0.239 0.236 0.258 0.391]
 [0.239 0.236 0.258 0.391]
 [0.239 0.236 0.258 0.391]
 [0.239 0.236 0.258 0.391]] 

c_k_matmul =
 [[2.72 2.57 1.58 2.71]
 [2.72 2.57 1.58 2.71]
 [2.72 2.57 1.58 2.71]
 [2.72 2.57 1.58 2.71]] 

d_k_matmul =
 [[2.068 1.498 1.57  1.75 ]
 [1.693 1.689 1.645 1.195]
 [1.984 1.578 1.562 1.318]
 [2.547 1.923 1.979 1.865]] 

Saved a_k_matmul to data/a_k_matmul.txt
Saved b_k_mat_matmul to data/b_k_mat_matmul.txt
Saved c_k_matmul to data/c_k_matmul.txt
Saved d_k_matmul to data/d_k_matmul.txt


We see that the matrix product between symmetric matrices isn't still symmetric.

In [7]:
# compute the eigenvalues and eigenvectors of product matrices
# ELEMENTWISE
with open('eigenvalues_and_eigenvectors.txt', 'w') as f:
    # ELEMENTWISE
    for name, matrix in zip(elementw_names, elementw_matrices):
        eigenvalues, eigenvectors = np.linalg.eig(matrix)
        f.write(f"Eigenvalues {name}:\n")
        f.write(np.array2string(eigenvalues, separator=', ') + '\n\n')
        f.write(f"Eigenvectors {name}:\n")
        f.write(np.array2string(eigenvectors, separator=', ') + '\n\n')
    
    # ROW-COLUMN PRODUCT
    for name, matrix in zip(rowcolumn_names, rowcolumn_matrices):
        eigenvalues, eigenvectors = np.linalg.eig(matrix)
        f.write(f"Eigenvalues {name}:\n")
        f.write(np.array2string(eigenvalues, separator=', ') + '\n\n')
        f.write(f"Eigenvectors {name}:\n")
        f.write(np.array2string(eigenvectors, separator=', ') + '\n\n')