In [3]:
import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
from libraries.graphs import graph_draw
from G_matrix import G
from K1_operator import K1

In [4]:
output_dir = "graphs"  # create a directory to save the plots
os.makedirs(output_dir, exist_ok=True)
if not os.path.exists("data"):  # create the data directory if it does not exist
    os.makedirs("data")

## 1. From healthy G and K, compute diseased G by K*G and K@K 

In [5]:
# here I suppose to have G and K, simple model, only one matrix 4x4 for the entire brain, I use the same function to 
# generate both matrices 
print(K1)
print("\n")
print(G)

plt.figure(1)
graph_draw(np.round(G, 2),
        Directed=False,
        Weighted=True,
        Index_on=True,
        Weight_on=False
        )
plt.title("healthy_G")
plt.savefig(os.path.join(output_dir, f"{"healthy_G"}.png"))
plt.close()

np.savetxt(os.path.join("data", "K1.txt"), K1)
np.savetxt(os.path.join("data", "G.txt"), G)

[[0.07 0.2  0.38 0.27]
 [0.1  0.19 0.35 0.9 ]
 [0.92 0.68 0.78 0.18]
 [0.98 0.83 0.09 0.59]]


[[1.   0.32 0.36 0.3 ]
 [0.32 1.   0.82 0.92]
 [0.36 0.82 1.   0.4 ]
 [0.3  0.92 0.4  1.  ]]


In [6]:
K1G = K1 * G # elementwise product to compute K 
K1_at_G_1 = K1 @ G # matrix product to compute K 

np.savetxt(os.path.join("data", "K1G.txt"), K1G)
np.savetxt(os.path.join("data", "K1_at_G_1.txt"), K1_at_G_1)
# to check whether the two operations in python (@ and np.matmul) are really the same
# G_at_K1_2 = np.matmul(G, K1)
# print(GK1)
# print(G_at_K1_1)
# print(G_at_K1_2)
# print(G_at_K1_1 == G_at_K1_2)

plt.figure(2)
graph_draw(np.round(K1G, 2),
        Directed=False,
        Weighted=True,
        Index_on=True,
        Weight_on=False
        )
plt.title("elementw_KG")
plt.savefig(os.path.join(output_dir, f"{"elementw_KG"}.png"))
plt.close()

plt.figure(3)
graph_draw(np.round(K1_at_G_1, 2),
        Directed=False,
        Weighted=True,
        Index_on=True,
        Weight_on=False
        )
plt.title("rowbycol_KG")
plt.savefig(os.path.join(output_dir, f"{"rowbycol_KG"}.png"))
plt.close()

In [7]:
with open('eigenvalues_and_eigenvectors.txt', 'w') as f:
    # ELEMENTWISE
    
    eigenval_K1G, eigenvec_K1G = np.linalg.eig(K1G)
    f.write(f"Eigenvalues {"elementw_KG"}:\n")
    f.write(np.array2string(eigenval_K1G, separator=', ') + '\n\n')
    f.write(f"Eigenvectors {"elementw_KG"}:\n")
    f.write(np.array2string(eigenvec_K1G, separator=', ') + '\n\n')
    
    # ROW-COLUMN PRODUCT

    eigenval_K1_at_G_1, eigenvec_K1_at_G_1 = np.linalg.eig(K1_at_G_1)
    f.write(f"Eigenvalues {"rowbycol_KG"}:\n")
    f.write(np.array2string(eigenval_K1_at_G_1, separator=', ') + '\n\n')
    f.write(f"Eigenvectors {"rowbycol_KG"}:\n")
    f.write(np.array2string(eigenvec_K1_at_G_1, separator=', ') + '\n\n')